export const laptopMockData = {
  display: "15.6-inch Full HD (1920 x 1080)",
  processor: "Intel Core i7 (13th Gen)",
  ram: "16 GB",
  storage: "512 GB",
  videoCard: "AMD Radeon Graphics",
  weight: "1.4 kg",
  fastCharge: "50% in 45 minutes",
  storageExpandable: false,
  graphicsCores: 10,
  resolutionType: "WQXGA (Higher than Full HD)",
  recommendedUsage: [
    "Photo Editing",
    "Music Production & DJing",
    "On the Go",
    "Spreadsheets & Presentations",
    "Study",
    "Video Editing",
  ],
  connectivity: ["Wi-Fi 6", "Bluetooth 5.1", "USB-C"],
  notes: [
    "You can edit photos and videos and multitask between heavy programs.",
    "1 terabyte recommended for more space; this model has 512 GB.",
    "Fast charging supports working wirelessly again quickly.",
    "WQXGA is sharper than Full HD, useful for detail visibility.",
    "Laptop is lightweight and portable.",
    "Choose 10 or more graphics cores for better performance.",
    "Not upgradeable for RAM or storage – less future-proof.",
  ],
};
